version: 2.1
jobs:
  build:
    docker:
      - image: golang:1.19.2-alpine3.16
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: go mod download
      - run:
          name: Run tests
          command: go test ./...